name: Autograding Tests
on: push:
  jobs:
    run-autograding-tests:
      runs-on: ubuntu-latest
      if: github.actor != 'github-classroom[bot]'
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Grade Quiz 1
          working-directory: ${{ github.workspace }}
          run: bash grade_quiz.sh
          id: grade-quiz
        - name: Autograding Reporter
          uses: classroom-resources/autograding-grading-reporter@v1
          env:
            QUIZ-1_RESULTS: "{\"score\":${{ steps.grade-quiz.outputs.quiz-1_score }},\"max_score\":${{ steps.grade-quiz.outputs.quiz-1_max_score }}}"
          with:
            runners: quiz-1
